Update (#1)
* Drop Jython/Python 2 and add Python 3.9/3.10

* Drop OrderedDict in Python >= 3.7

* Fix typo

* Do not use `len()` to determine if a sequence is empty

* Add more namespace attribute tests

* setup: open README.md with a specific encoding

With python3, the built-in open() function opens files in "text" mode by
default (i.e. the f.read() method reads bytes and tries to decode them
to unicode using the interpreter default encoding). Depending on the
system locale, this default encoding may be 'ascii'. Which leads to the
following error:

 ~$ python3 setup.py egg_info
 Traceback (most recent call last):
   File "setup.py", line 12, in <module>
     long_description = f.read()
   File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
     return codecs.ascii_decode(input, self.errors)[0]
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position
 2587: ordinal not in range(128)

The character at position 2587 is 'ô' (from Fantômas) and is utf-8
encoded.

Force to open the file in "binary" mode (which is the only mode on
python2) and explicitly decode the read bytes to unicode using the
'utf-8' codec.

Fixes: 8374e7d84f92 ("Use Markdown long_description on PyPI (#190)")
Signed-off-by: Robin Jarry <robin.jarry@6wind.com>

* Bump version and update CHANGELOG.

* Update push_release.sh to use twine.

* Fix Travis CI status badge URL

Fixes #296

* fix attributes not appearing in streaming mode

* Add test coverage for #278

* added conda installation command

* Ensure significant whitespace is not trimmed

* Enable `python -m unittest tests/*.py`

Without this, `python -m unittest tests/*.py` would complain
`ModuleNotFoundError: No module named 'tests.test_dicttoxml'`

* Support indent using interger format

Originally `unparse(pretty=True, indent=2)` would fail
with confusing error message,
as it only supported `unparse(pretty=True, indent='  ')`

This commit adds support for int indent

---------

Signed-off-by: Robin Jarry <robin.jarry@6wind.com>
Co-authored-by: Martin Blech <78768+martinblech@users.noreply.github.com>
Co-authored-by: Kian-Meng, Ang <kianmeng@cpan.org>
Co-authored-by: Dimitri Papadopoulos <3234522+DimitriPapadopoulos@users.noreply.github.com>
Co-authored-by: leogregianin <leogregianin@gmail.com>
Co-authored-by: Robin Jarry <robin.jarry@6wind.com>
Co-authored-by: timnguyen <timnguyen001@gmail.com>
Co-authored-by: Sugato Ray <sugatoray@users.noreply.github.com>
Co-authored-by: Trey Franklin <trey.franklin@adtran.com>
Co-authored-by: hiiwave <hiiwave@gmail.com>